### ISSUE TITLE
thread 'main' panicked at 'slice index starts at 18446744073709551614 but ends at 123', src/tag.rs:108:39

### ISSUE THREAD

**Issue by maja-glotz** [dohlee/metheor#17]
Hello!

I am using the metheor package for calculating the Epipolymorphism score on WGBS data. Since my BAM files were not aligned with bismark, I need to add the bismark XM tag with your corresponding command `metheor tag` first. 

I don't know why, but somehow my BAM files only contained data for chromosome 1-3 after XM tagging. So I split my BAM file into 23 single files for each chromosome respectively and then applied the XM tagging command individually. This worked perfectly fine for every chromosome, except for chromosome 17, where I got the following error and the output BAM was empty.

thread 'main' panicked at 'slice index starts at 18446744073709551614 but ends at 123', src/tag.rs:108:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Maybe you could help me find the source of the error. Many thanks in advance!

Best regards,
Maja

**Comment by dohlee** [comment]
Thanks for your interest in Metheor. I'll look into the issue and get back to you.
By the way, could you please provide a minimal BAM file to reproduce the error from chromosome 17? It may help a lot.

Thanks
Dohoon

**Comment by maja-glotz** [comment]
Hello!

Please excuse the late reply. Unfortunately, due to data protection I cannot provide you a subset of the BAM file. If you still have any idea what may cause the problem , I'd be happy to hear from you anyways!

Thanks in advance
Maja
